apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: cafe
type: Opaque
stringData:
  SECRET_KEY: "super-secret-key-change-me"   # сюда можешь вставить свой из .env
  DEBUG: "0"                                 # прод-режим
  ALLOWED_HOSTS: "*"                         # разрешаем все хосты
